# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
    - name: Load GH_TOKEN from secrets
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: echo GH_TOKEN=$GH_TOKEN >> ./gradle.properties
    - name: Build Gradle Jar
      run: ./gradlew build
    - name: List reobfJar
      run: ls -a ./build && ls -a ./build/libs
    - name: Get plugin version
      run: echo ::set-output name=version::$(./gradlew properties -q | grep "mod_version:" | awk '{print $2}')
      id: plugin_version
    - name: Get Short Commit Hash
      id: commit_hash
      run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
    - name: Generate release tag
      id: tag
      run: |
        echo "::set-output name=release_tag::Inventories_fabric_${{ steps.plugin_version.outputs.version }}_${{ steps.commit_hash.outputs.sha_short }}"
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: ./build/libs/inventories-${{ steps.plugin_version.outputs.version }}-fabric.jar
        tag_name: ${{ steps.tag.outputs.release_tag }}
        token: ${{ secrets.GH_TOKEN }}